### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by jbkunst** [pachamaltese/mindicador#2]
Algunos pensamientos que me han aparecidop luego del uso.

1. ¿Es necesario que el output del data frame sea data.table? ¿No es un poco invasivo (para quien usa Rbase o quizás tidyverse)? Podría ser un data.frame de los de viejo antaño.
2. Me hizo un poco de ruido que el output data frame venga ordenado por fecha de forma descendente. Si lo exportara a un excel lo esperaría de forma ascendente (bueno, quizás soy solamente yo).

Saludos,

**Comment by pachamaltese** [comment]
@jbkunst gracias x el comentario, voy a implementar esos cambios :)

**Comment by jbkunst** [comment]
Hola @pachamaltese 

Con respecto al punto 2. El data frame preserva el orden previo al parecer.

``` r

df <- mindicador::mindicador_importar_datos("tasa_desempleo", anios = 2020)

df
#>            serie      fecha valor
#> 6 tasa_desempleo 2020-01-01  7.43
#> 5 tasa_desempleo 2020-02-01  7.81
#> 4 tasa_desempleo 2020-03-01  8.23
#> 3 tasa_desempleo 2020-04-01  9.00
#> 2 tasa_desempleo 2020-05-01 11.21
#> 1 tasa_desempleo 2020-06-01 12.25

rownames(df) <- NULL

df
#>            serie      fecha valor
#> 1 tasa_desempleo 2020-01-01  7.43
#> 2 tasa_desempleo 2020-02-01  7.81
#> 3 tasa_desempleo 2020-03-01  8.23
#> 4 tasa_desempleo 2020-04-01  9.00
#> 5 tasa_desempleo 2020-05-01 11.21
#> 6 tasa_desempleo 2020-06-01 12.25
```

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pachamaltese** [comment]
Ahora si cambié el punto 2 en 73ec016
