### ISSUE TITLE
Problema con indicador dolar_intercambio

### ISSUE THREAD

**Issue by jbkunst** [pachamaltese/mindicador#3]
Hola 

``` r
packageVersion("mindicador")
#> [1] '0.1.7'
mindicador::mindicador_importar_datos("dolar_intercambio")
#> Error in as.Date.default(d$fecha): do not know how to convert 'd$fecha' to class "Date"
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pachamaltese** [comment]
gracias

pasa que esa serie llega hasta 2014, acabo de revisar, voy a escribir al
autor de la API

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by jbkunst** [comment]
@pachamaltese , Ahora si considero la tasa de desempleo para 2021:

(tb ocurre con 0.1.7)

``` r
mindicador::mindicador_importar_datos("tasa_desempleo", anios = 2020)
#>              serie      fecha valor
#>  1: tasa_desempleo 2020-12-01 10.29
#>  2: tasa_desempleo 2020-11-01 10.76
#>  3: tasa_desempleo 2020-10-01 11.58
#>  4: tasa_desempleo 2020-09-01 12.35
#>  5: tasa_desempleo 2020-08-01 12.93
#>  6: tasa_desempleo 2020-07-01 13.09
#>  7: tasa_desempleo 2020-06-01 12.25
#>  8: tasa_desempleo 2020-05-01 11.21
#>  9: tasa_desempleo 2020-04-01  9.00
#> 10: tasa_desempleo 2020-03-01  8.23
#> 11: tasa_desempleo 2020-02-01  7.81
#> 12: tasa_desempleo 2020-01-01  7.43
mindicador::mindicador_importar_datos("tasa_desempleo", anios = 2021)
#> Error in as.Date.default(d$fecha): do not know how to convert 'd$fecha' to class "Date"
packageVersion("mindicador")
#> [1] '0.1.5'
```

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pachamaltese** [comment]
@jbkunst  tanto tiempo XD
me pillaste almorzando, dame unos minutos y lo veo

**Comment by pachamaltese** [comment]
@jbkunst debería decir
"no hay datos para el periodo solicitado"
es un tema de que no están cargados los datos 2021

**Comment by pachamaltese** [comment]
@jbkunst prueba `remotes::install_github("pachamaltese/mindicador")` pues la v0.1.8 es la última en GH
actualizaré en CRAN este finde
